# Generated by Django 5.0.7 on 2024-08-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_cinema_shows_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_poster2',
            field=models.ImageField(default='movies/poster/not.jpg', upload_to='movies/poster'),
        ),
    ]
